keywords = [
    "moonman",
    "14 words",
    "feminazi",
    "stand united",
    "savage",
    "degenerate",
    "incels",
    "mgtow",
    "anti-muslim",
    "anti-semitism",
    "holy war",
    "go back to your country",
    "lgbt",
    "racial superiority",
    "globalist agenda",
    "blood and honour",
    "homophobia",
    "marxism",
    "jihadist",
    "invaders",
    "defend your rights",
    "protect our heritage",
    "rise up",
    "misogyny",
    "race traitor",
    "kill",
    "anti-women",
    "patriot",
    "88",
    "rape",
    "violent",
    "alt-right",
    "men's rights activism",
    "exterminate",
    "beta male",
    "atomwaffen division",
    "subhuman",
    "neo-nazi",
    "6 million wasn't enough",
    "white supremacy",
    "religious war",
    "ethnic cleansing",
    "rahowa",
    "white nationalism",
    "christophobia",
    "crusader",
    "patriot movement",
    "zionist",
    "defend our race",
    "militia",
    "cleansing our culture",
    "martyr",
    "infidel",
    "anchor baby",
    "agenda",
    "join the fight",
    "proud boys",
    "illegal alien",
    "islamophobia",
    "race war",
    "hate speech",
    "holocaust",
    "hypergamy",
    "hammerskins",
    "civil war",
    "stormfront",
    "parasites",
    "identity evropa",
    "take action now",
    "racial",
    "jewish",
    "alpha male",
    "qanon",
    "cultural marxism",
    "christian",
    "blood and soil",
    "heathen",
    "jewish conspiracy",
    "ku klux klan",
    "new world order",
    "build the wall",
    "inferior",
    "replacement theory",
    "supremacy",
    "take our jobs",
    "white nationalist",
    "lesbian",
    "anti-lgbtq",
    "gay",
    "illuminati",
    "racial slurs",
    "conspiracy",
    "aryan brotherhood",
    "boogaloo",
    "day of the rope",
    "genocide",
    "chad",
    "foreigners",
    "infestation",
    "cockroaches",
    "nationalism",
    "black pill",
    "oath keepers",
    "stacy",
    "anti-immigrant",
    "deep state",
    "far-right",
    "cockroach",
    "cultural war",
    "white genocide",
    "black-on-white",
    "take back our country",
    "transphobia",
    "red pill",
    "fight against immigration",
    "blood & honour",
    "immigrants are invading",
    "revolution",
    "parasite",
    "fascism",
    "uprising"
]
