hate_keywords = [
    "14",
    "88",
    "agenda",
    "alt-right",
    "anchor",
    "American",
    "anti-elitism",
    "anti-feminism",
    "anti-globalism",
    "anti-immigrant",
    "anti-immigration",
    "anti-lgbtq",
    "anti-muslim",
    "anti-sjw",
    "anti-social",
    "anti-semitism",
    "authoritarian",
    "Aryan",
    "beta",
    "black",
    "blood",
    "bloodlines",
    "blood & honour",
    "boy",
    "boys",
    "caravan",
    "Chad",
    "Christian",
    "Christian nationalism",
    "citizenship",
    "cleansing",
    "conservative",
    "conspiracy",
    "cultural appropriation",
    "cultural decline",
    "cultural identity",
    "cultural marxism",
    "cultural war",
    "cultural warriors",
    "degenerate",
    "deep",
    "defend",
    "defend our race",
    "defend the nation",
    "defend your rights",
    "disruption",
    "ethnic",
    "ethnic cleansing",
    "ethnic identity",
    "Eurocentrism",
    "exterminate",
    "exclusivity",
    "family",
    "family first",
    "family structure",
    "fascism",
    "feminazi",
    "freedom",
    "freedom fighter",
    "freedom of speech",
    "fight",
    "fight against immigration",
    "gender",
    "gender critical",
    "great",
    "hate",
    "hate speech",
    "heritage",
    "heritage not hate",
    "heathen",
    "historical",
    "historical revisionism",
    "honor",
    "immigrants",
    "immigration",
    "invasion",
    "invaders",
    "Islam",
    "islamophobia",
    "identity",
    "identity evropa",
    "identity politics",
    "illumination",
    "illegals",
    "Illuminati",
    "jihadist",
    "Jewish",
    "Jewish conspiracy",
    "ku klux klan",
    "liberal",
    "life",
    "lives",
    "masculinity",
    "men's",
    "migration",
    "militia",
    "misogyny",
    "moral",
    "moral decay",
    "nationalism",
    "national",
    "national pride",
    "national sovereignty",
    "new world order",
    "patriarchal",
    "patriarchal values",
    "political",
    "political correctness",
    "populism",
    "pride",
    "pro",
    "pro-white",
    "protect",
    "protecting",
    "qanon",
    "race",
    "race consciousness",
    "race traitor",
    "race war",
    "racial",
    "racial purity",
    "racial slurs",
    "racial superiority",
    "racial profiling",
    "revolution",
    "reclaiming",
    "rights",
    "right",
    "rise",
    "rise up",
    "Roman",
    "savage",
    "self-defense",
    "sovereignty",
    "stormfront",
    "stacy",
    "subhuman",
    "take",
    "take action now",
    "take back our country",
    "take our jobs",
    "taking",
    "traditional",
    "transphobia",
    "tribalism",
    "Trump",
    "uprising",
    "violence",
    "violent",
    "war",
    "war on Christmas",
    "white",
    "white genocide",
    "white history",
    "white lives matter",
    "white nationalism",
    "white pride",
    "women's",
    "woke",
    "xenophobia",
    "zionist",
]

nonhate_keywords = [
    "science experiments",
    "history lessons",
    "math tutorials",
    "physics concepts",
    "chemistry basics",
    "language learning",
    "healthy recipes",
    "cooking tips",
    "fitness training",
    "programming lessons",
    "puzzle solutions",
    "coding tutorials",
    "space missions",
    "renewable energy",
    "biology studies",
    "climate action",
    "earth sciences",
    "global warming",
    "mind exercises",
    "goal setting",
    "career tips",
    "writing skills",
    "positive habits",
    "time management",
    "life advice",
    "health tips",
    "mental wellness",
    "weight management",
    "stress relief",
    "yoga sessions",
    "movie reviews",
    "funny sketches",
    "camping tips",
    "travel guides",
    "gardening advice",
    "art tutorials",
    "musical instruments",
    "DIY crafts",
    "robotics innovations",
    "quantum physics",
    "coding challenges",
    "book reviews",
    "creative writing",
    "financial planning",
    "career planning",
    "self growth",
    "confidence building",
    "social skills",
    "online courses",
    "video editing",
    "graphic design",
    "solar power",
    "clean energy",
    "electric vehicles",
    "coding basics",
    "space exploration",
    "ocean conservation",
    "wildlife protection",
    "forest restoration",
    "urban gardening",
    "public speaking",
    "leadership qualities",
    "time blocking",
    "study techniques",
    "brain training",
    "memory improvement",
    "data science",
    "machine learning",
    "artificial intelligence",
    "robot programming",
    "business strategies",
    "marketing tips",
    "sales techniques",
    "goal achievement",
    "healthy habits",
    "emotional intelligence",
    "stress management",
    "fitness plans",
    "nutrition advice",
    "self discipline",
    "personal branding",
    "art appreciation",
    "creative hobbies",
    "online education",
    "music production",
    "photography basics",
    "video production",
    "digital marketing",
    "financial literacy",
    "math puzzles",
    "science facts",
    "coding projects",
    "ethical hacking",
    "web development",
    "app development",
    "solar installation",
    "energy efficiency",
    "planet conservation",
    "astronomy facts",
    "space discoveries",
    "galaxy exploration",
    "stargazing tips",
    "ocean life",
    "marine conservation",
    "recycling ideas",
    "sustainable solutions",
    "urban farming",
    "zero waste",
    "electric cars",
    "future technology",
    "coding competitions",
    "logic puzzles",
    "algorithm design",
    "career advice",
    "resume building",
    "job interviews",
    "interview preparation",
    "team building",
    "mental clarity",
    "brainstorming techniques",
    "creativity exercises",
    "empathy training",
    "negotiation skills",
    "critical thinking",
    "storytelling techniques",
    "visual storytelling",
    "productivity hacks",
    "habit formation",
    "self motivation",
    "workout plans",
    "weight training",
    "nutrition planning",
    "healthy snacks",
    "meal prep",
    "active lifestyle",
    "lifestyle changes",
    "adventure travel",
    "outdoor activities",
    "nature trails",
    "wildlife adventures",
    "mountain climbing",
    "bird watching",
    "lake exploration",
    "desert safaris",
    "skydiving tips",
    "trekking guides",
    "water sports",
    "cycling adventures",
    "road trips",
    "campfire cooking",
    "urban exploring",
    "city tours",
    "world heritage",
    "cultural immersion",
    "language immersion",
    "hobby tutorials",
    "art skills",
    "color theory",
    "3D modeling",
    "film making",
    "audio mixing",
    "guitar lessons",
    "piano tutorials",
    "violin techniques",
    "flute basics",
    "singing tips",
    "songwriting techniques",
    "lyric writing",
    "home improvements",
    "kitchen organization",
    "small spaces",
    "home decor",
    "budget planning",
    "investment strategies",
    "crypto basics",
    "stock market",
    "trading tips",
    "financial independence",
    "retirement planning",
    "passive income",
    "personal finance",
    "money management",
    "life coaching",
    "mindful living",
    "meditation techniques",
    "gratitude journaling",
    "positive affirmations",
    "emotional balance",
    "mental health",
    "social confidence",
    "relationship tips",
    "parenting advice",
    "child education",
    "reading comprehension",
    "study hacks",
    "exam preparation",
    "learning techniques",
    "language tips",
    "accent training",
    "pronunciation guides",
    "grammar basics",
    "vocabulary building",
    "essay writing",
    "speech writing",
    "debate skills",
    "presentation skills",
]
